# DAST Workflow for the DevSecOps & Cloud Security course

name: Running DAST tools

on:
  workflow_call:
    secrets:
      HAWK_API_KEY:
        required: true

jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v2.0.0
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
  zap_scan:
    runs-on: ubuntu-latest
    needs: hawkscan
    name: Scan ZAP website
    permissions:
      security-events: write
    container:
      image: owasp/zap2docker-stable
      options: --user root -v ${{ github.workspace }}:/zap/wrk/:rw
    steps:
      - run: pwd && ls -l
      - name: run zap baseline scan
        run: zap-baseline.py -t https://sergiocayuqueo.herokuapp.com -x report_xml.xml || echo 0
  
  zap_dast_scan:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: 🔍 Owasp Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log current directory
      run: echo ${pwd}
    - name: Pull Docker image for ZAP
      run: docker pull owasp/zap2docker-weekly
    - name: Sleep for deployment completition
      run: sleep 60s
      shell: bash
    - name: Run zap scan
      run: docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t https://sergiocayuqueo.herokuapp.com -g gen.conf -r zapreport.html
      continue-on-error: true 
    - uses: actions/upload-artifact@v2
      name: upload ZAP report
      with:
        name: ZAPreport
        path: zapreport.html
