# SAST Workflow for the DevSecOps & Cloud Security course

name: Running SAST tools

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  trivy:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status 
    name: Trivy scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
  checkov:
    name: Checkov scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run checkov scanner
        uses: bridgecrewio/checkov-action@master
        continue-on-error: true 
        with:
          directory: .
          framework: all
          quiet: true
          soft_fail: true
          download_external_modules: true
          output_format: sarif
  secrets-scanner:
    name: Scan for secrets using gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
        continue-on-error: true
  snyk:
    name: Snyk scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run npm install before scanning
        run: npm install
      - name: Run Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
