# DAST Workflow for the DevSecOps & Cloud Security course

name: Running DAST tools

on:
  workflow_call:
    secrets:
      HAWK_API_KEY:
        required: true

jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v2.0.0
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
